In [3]:
import sklearn
import numpy as np
import pandas as pd

In [1]:
mri_csv = pd.read_csv('archive/oasis_longitudinal.csv')
mri_csv['Group'].replace('Converted', 'Demented', inplace=True)

NameError: name 'pd' is not defined

In [45]:
mri_csv.describe()

Visit     MR Delay         Age        EDUC         SES  \
count  373.000000   373.000000  373.000000  373.000000  354.000000   
mean     1.882038   595.104558   77.013405   14.597855    2.460452   
std      0.922843   635.485118    7.640957    2.876339    1.134005   
min      1.000000     0.000000   60.000000    6.000000    1.000000   
25%      1.000000     0.000000   71.000000   12.000000    2.000000   
50%      2.000000   552.000000   77.000000   15.000000    2.000000   
75%      2.000000   873.000000   82.000000   16.000000    3.000000   
max      5.000000  2639.000000   98.000000   23.000000    5.000000   

             MMSE         CDR         eTIV        nWBV         ASF  
count  371.000000  373.000000   373.000000  373.000000  373.000000  
mean    27.342318    0.290885  1488.128686    0.729568    1.195461  
std      3.683244    0.374557   176.139286    0.037135    0.138092  
min      4.000000    0.000000  1106.000000    0.644000    0.876000  
25%     27.000000    0.000000  1357.000000    0.700000    1.099000  
50%     29.000000    0.000000  1470.000000    0.729000    1.194000  
75%     30.000000    0.500000  1597.000000    0.756000    1.293000  
max     30.000000    2.000000  2004.000000    0.837000    1.587000

In [46]:
mri_csv = mri_csv.dropna()
mri_csv.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 354 entries, 0 to 372
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Subject ID  354 non-null    object 
 1   MRI ID      354 non-null    object 
 2   Group       354 non-null    object 
 3   Visit       354 non-null    int64  
 4   MR Delay    354 non-null    int64  
 5   M/F         354 non-null    object 
 6   Hand        354 non-null    object 
 7   Age         354 non-null    int64  
 8   EDUC        354 non-null    int64  
 9   SES         354 non-null    float64
 10  MMSE        354 non-null    float64
 11  CDR         354 non-null    float64
 12  eTIV        354 non-null    int64  
 13  nWBV        354 non-null    float64
 14  ASF         354 non-null    float64
dtypes: float64(5), int64(5), object(5)
memory usage: 44.2+ KB


In [47]:
from sklearn import preprocessing

In [136]:
y = mri_csv['Group']
le_y = preprocessing.LabelEncoder()
le_y.fit(y)
y = le_y.transform(y)
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1,

In [137]:
X = mri_csv.iloc[:, 5:]
le_MF = preprocessing.LabelEncoder()
le_MF.fit(X['M/F'])
X['M/F'] = le_MF.transform(X['M/F'])
X.drop('Hand', inplace=True, axis=1)
X

M/F  Age  EDUC  SES  MMSE  CDR  eTIV   nWBV    ASF
0      1   87    14  2.0  27.0  0.0  1987  0.696  0.883
1      1   88    14  2.0  30.0  0.0  2004  0.681  0.876
5      0   88    18  3.0  28.0  0.0  1215  0.710  1.444
6      0   90    18  3.0  27.0  0.0  1200  0.718  1.462
7      1   80    12  4.0  28.0  0.0  1689  0.712  1.039
..   ...  ...   ...  ...   ...  ...   ...    ...    ...
368    1   82    16  1.0  28.0  0.5  1693  0.694  1.037
369    1   86    16  1.0  26.0  0.5  1688  0.675  1.040
370    0   61    13  2.0  30.0  0.0  1319  0.801  1.331
371    0   63    13  2.0  30.0  0.0  1327  0.796  1.323
372    0   65    13  2.0  30.0  0.0  1333  0.801  1.317

[354 rows x 9 columns]

In [138]:
def accuracy(y_true, y_pred):
    return np.sum(y_true == y_pred) / len(y_true)

In [84]:
GaussianNB?

In [214]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, roc_auc_score, precision_score, f1_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=True, random_state=2)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

list(le_y.inverse_transform(y_pred))
accuracy(y_pred, y_test)
print(pd.DataFrame(data=[accuracy_score(y_test, y_pred), recall_score(y_test, y_pred),
                   precision_score(y_test, y_pred), roc_auc_score(y_test, y_pred), f1_score(y_test, y_pred)],
             index=["accuracy", "recall", "precision", "roc_auc_score", "f1"]))

                      0
accuracy       0.971963
recall         0.981132
precision      0.962963
roc_auc_score  0.972048
f1             0.971963


In [232]:
from sklearn.feature_selection import VarianceThreshold

thresholder = VarianceThreshold(threshold=0.4)

X_high_variance = thresholder.fit_transform(X)
print(X_high_variance[0:7])

[[8.700e+01 1.400e+01 2.000e+00 2.700e+01 1.987e+03]
 [8.800e+01 1.400e+01 2.000e+00 3.000e+01 2.004e+03]
 [8.800e+01 1.800e+01 3.000e+00 2.800e+01 1.215e+03]
 [9.000e+01 1.800e+01 3.000e+00 2.700e+01 1.200e+03]
 [8.000e+01 1.200e+01 4.000e+00 2.800e+01 1.689e+03]
 [8.300e+01 1.200e+01 4.000e+00 2.900e+01 1.701e+03]
 [8.500e+01 1.200e+01 4.000e+00 3.000e+01 1.699e+03]]


In [233]:
X_train, X_test, y_train, y_test = train_test_split(X_high_variance, y, test_size=0.3, shuffle=True, random_state=4)
gnb = GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_test)

list(le_y.inverse_transform(y_pred))
print(pd.DataFrame(data=[accuracy_score(y_test, y_pred), recall_score(y_test, y_pred),
                   precision_score(y_test, y_pred), roc_auc_score(y_test, y_pred), f1_score(y_test, y_pred)],
             index=["accuracy", "recall", "precision", "roc_auc_score", "f1"]))

                      0
accuracy       0.822430
recall         0.941176
precision      0.750000
roc_auc_score  0.827731
f1             0.834783
